# Generated by Django 3.2.8 on 2022-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220218_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='points',
            field=models.IntegerField(default=0, max_length=5000),
        ),
        migrations.AddField(
            model_name='myuser',
            name='stars',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
