# Generated by Django 3.2.8 on 2022-02-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220219_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
