# Generated by Django 3.2.8 on 2022-02-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_push_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_push_token',
        ),
    ]
