# Generated by Django 3.2.8 on 2022-02-18 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220219_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitute', models.FloatField()),
                ('safety_score', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AuditForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting', models.PositiveIntegerField()),
                ('openness', models.PositiveIntegerField()),
                ('visibility', models.PositiveIntegerField()),
                ('people', models.PositiveIntegerField()),
                ('security', models.PositiveIntegerField()),
                ('walk_path', models.PositiveIntegerField()),
                ('public_transport', models.PositiveIntegerField()),
                ('public_usage', models.PositiveIntegerField()),
                ('feeling', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
    ]
